// VELTRA Specialty Configurations
// Each specialty changes: brief, patient conditions, lab types, procedures, billing items, timeline events
// Same engine, different data.

export type SpecialtyId =
  | "dental" | "general" | "cardiology" | "pediatrics" | "obgyn"
  | "orthopedics" | "ophthalmology" | "neurology" | "internal" | "dermatology"
  | "oral-surgery" | "endocrinology" | "pulmonology" | "hematology"
  | "gastroenterology" | "ent" | "physiotherapy" | "cosmetic" | "multi";

export interface SpecialtyConfig {
  id: SpecialtyId;
  name: string;
  icon: string;
  emoji: string;
  color: string;
  brief: {
    greeting: string;
    items: string[];
    revenue: number;
  };
  conditions: string[];
  procedures: string[];
  labTypes: string[];
  billingItems: { name: string; price: number }[];
  timelineEvents: string[];
  patientNames: string[];
  doctorName: string;
}

export const SPECIALTIES: SpecialtyConfig[] = [
  {
    id: "dental",
    name: "Dental",
    icon: "🦷",
    emoji: "🦷",
    color: "bg-sky-500/15 text-sky-300",
    brief: {
      greeting: "Good morning",
      items: [
        "4 Crown follow-ups today",
        "2 Root canal appointments",
        "Lab received 3 digital X-rays",
        "One implant patient missed yesterday",
        "Chair #3 becomes available at 2:30 PM",
      ],
      revenue: 8420,
    },
    conditions: ["Root Canal", "Orthodontics", "Implant", "Crown", "Whitening", "Extraction", "Gum Disease", "Cavity"],
    procedures: ["Root Canal", "Crown Fitting", "Implant Surgery", "Tooth Extraction", "Whitening", "Cleaning", "Filling", "Bridge"],
    labTypes: ["Panoramic X-ray", "CBCT Scan", "Intraoral Scan", "Digital Impression", "Periapical X-ray"],
    billingItems: [
      { name: "Implant", price: 1800 },
      { name: "Crown", price: 550 },
      { name: "Whitening", price: 300 },
      { name: "Root Canal", price: 900 },
      { name: "Extraction", price: 200 },
      { name: "Cleaning", price: 120 },
    ],
    timelineEvents: ["Patient seated", "X-ray uploaded", "Treatment plan approved", "Insurance verified", "Procedure completed", "Follow-up in 14 days"],
    patientNames: ["Ahmed Al-Farsi", "Sarah Chen", "Khalid Al-Otaibi", "Fatima Hassan", "John Doe", "Nora Al-Salem"],
    doctorName: "Dr. Ahmed",
  },
  {
    id: "general",
    name: "General Practice",
    icon: "🏥",
    emoji: "🏥",
    color: "bg-emerald-500/15 text-emerald-300",
    brief: {
      greeting: "Good morning",
      items: [
        "8 consultations today",
        "3 lab results pending review",
        "2 annual physicals scheduled",
        "Vaccination due for 4 patients",
      ],
      revenue: 4200,
    },
    conditions: ["Hypertension", "Diabetes", "Flu", "Allergies", "Migraine", "Back Pain"],
    procedures: ["Consultation", "Annual Physical", "Vaccination", "Wound Care", "Health Screening"],
    labTypes: ["Blood Panel", "Urine Analysis", "Lipid Panel", "HbA1c", "Thyroid Panel"],
    billingItems: [
      { name: "Consultation", price: 150 },
      { name: "Annual Physical", price: 350 },
      { name: "Vaccination", price: 80 },
      { name: "Health Screening", price: 500 },
    ],
    timelineEvents: ["Patient checked in", "Vitals recorded", "Consultation completed", "Prescription sent", "Follow-up scheduled"],
    patientNames: ["James Wilson", "Mary Johnson", "Robert Lee", "Patricia Kim", "David Brown"],
    doctorName: "Dr. Sarah",
  },
  {
    id: "cardiology",
    name: "Cardiology",
    icon: "❤️",
    emoji: "❤️",
    color: "bg-red-500/15 text-red-300",
    brief: {
      greeting: "Good morning",
      items: [
        "2 ECG reviews today",
        "Troponin result received",
        "Echo scheduled for 11 AM",
        "High-risk patient overdue for follow-up",
      ],
      revenue: 9800,
    },
    conditions: ["Hypertension", "Arrhythmia", "Heart Failure", "Coronary Disease", "Valve Disease"],
    procedures: ["ECG", "Echocardiogram", "Stress Test", "Holter Monitor", "Cardiac Consultation"],
    labTypes: ["ECG", "Echocardiogram", "Holter Monitor", "Stress Test", "Troponin", "Lipid Panel", "BNP"],
    billingItems: [
      { name: "Echocardiogram", price: 800 },
      { name: "ECG", price: 150 },
      { name: "Stress Test", price: 600 },
      { name: "Holter Monitor", price: 450 },
      { name: "Consultation", price: 300 },
    ],
    timelineEvents: ["ECG performed", "Echo reviewed", "Medication adjusted", "Cardiac rehab discussed", "Follow-up in 30 days"],
    patientNames: ["Robert Taylor", "Hassan Ali", "Margaret Chen", "Omar Khalil", "Evelyn Park"],
    doctorName: "Dr. Omar",
  },
  {
    id: "pediatrics",
    name: "Pediatrics",
    icon: "👶",
    emoji: "👶",
    color: "bg-amber-500/15 text-amber-300",
    brief: {
      greeting: "Good morning",
      items: [
        "3 vaccinations due today",
        "Growth chart updated for 5 patients",
        "Fever follow-up at 10 AM",
        "2 school medical reports requested",
      ],
      revenue: 3100,
    },
    conditions: ["Fever", "Asthma", "Eczema", "Ear Infection", "Vaccination Due", "Growth Concern"],
    procedures: ["Vaccination", "Well-Child Visit", "School Medical", "Growth Assessment", "Developmental Screening"],
    labTypes: ["CBC", "Lead Test", "Allergy Panel", "Stool Culture", "Throat Swab"],
    billingItems: [
      { name: "Vaccination", price: 80 },
      { name: "Well-Child Visit", price: 200 },
      { name: "School Medical", price: 100 },
      { name: "Developmental Screening", price: 250 },
    ],
    timelineEvents: ["Child weighed and measured", "Vaccination administered", "Growth chart updated", "Parent counseled", "Next visit in 3 months"],
    patientNames: ["Emma Wilson", "Liam Garcia", "Sophia Patel", "Noah Kim", "Olivia Brown"],
    doctorName: "Dr. Layla",
  },
  {
    id: "dermatology",
    name: "Dermatology",
    icon: "🩹",
    emoji: "🩹",
    color: "bg-orange-500/15 text-orange-300",
    brief: {
      greeting: "Good morning",
      items: [
        "3 Botox follow-ups today",
        "1 Mole biopsy result received",
        "2 Laser sessions confirmed",
        "Acne review due for 4 patients",
      ],
      revenue: 6700,
    },
    conditions: ["Acne", "Psoriasis", "Eczema", "Melanoma", "Rosacea", "Botox", "Fillers"],
    procedures: ["Botox Injection", "Laser Therapy", "Skin Biopsy", "Chemical Peel", "Filler Injection", "Cryotherapy"],
    labTypes: ["Skin Biopsy", "Histopathology", "Allergy Patch Test", "Fungal Culture", "Wood's Lamp Exam"],
    billingItems: [
      { name: "Botox", price: 450 },
      { name: "Laser Session", price: 600 },
      { name: "Skin Biopsy", price: 350 },
      { name: "Chemical Peel", price: 250 },
      { name: "Filler", price: 700 },
    ],
    timelineEvents: ["Skin examined", "Photos taken", "Biopsy performed", "Treatment plan discussed", "Follow-up in 4 weeks"],
    patientNames: ["Jennifer Adams", "Michael Ross", "Aisha Mohamed", "Daniel Cohen", "Rachel Green"],
    doctorName: "Dr. Sarah",
  },
  {
    id: "cosmetic",
    name: "Cosmetic Clinic",
    icon: "💉",
    emoji: "💉",
    color: "bg-pink-500/15 text-pink-300",
    brief: {
      greeting: "Good morning",
      items: [
        "Botox stock expires tomorrow",
        "Lip filler follow-up at 10 AM",
        "New consultation booked",
        "Laser maintenance due",
      ],
      revenue: 12400,
    },
    conditions: ["Wrinkles", "Volume Loss", "Hyperpigmentation", "Scarring", "Hair Loss"],
    procedures: ["Botox", "Dermal Fillers", "Laser Resurfacing", "PRP Therapy", "Microneedling", "Body Contouring"],
    labTypes: ["Allergy Test", "Blood Panel", "Hormone Panel"],
    billingItems: [
      { name: "Botox", price: 450 },
      { name: "Filler", price: 700 },
      { name: "Laser Resurfacing", price: 1200 },
      { name: "PRP Therapy", price: 900 },
      { name: "Body Contouring", price: 2500 },
    ],
    timelineEvents: ["Consultation completed", "Before photos taken", "Procedure performed", "After care explained", "Follow-up in 2 weeks"],
    patientNames: ["Victoria Beck", "Sandra Lee", "Christina Yang", "Mark Sloan", "Izzie Stevens"],
    doctorName: "Dr. Christina",
  },
  {
    id: "ophthalmology",
    name: "Ophthalmology",
    icon: "👁️",
    emoji: "👁️",
    color: "bg-cyan-500/15 text-cyan-300",
    brief: {
      greeting: "Good morning",
      items: [
        "3 Cataract consultations today",
        "Retina scan received",
        "Glaucoma follow-up at 2 PM",
        "LASIK assessment scheduled",
      ],
      revenue: 7200,
    },
    conditions: ["Cataract", "Glaucoma", "Myopia", "Diabetic Retinopathy", "Macular Degeneration"],
    procedures: ["Cataract Surgery", "LASIK", "Eye Exam", "Retinal Laser", "Intraocular Injection"],
    labTypes: ["Visual Acuity Test", "Retina Scan", "OCT", "Tonometry", "Slit Lamp Exam", "Visual Field Test"],
    billingItems: [
      { name: "Cataract Surgery", price: 3500 },
      { name: "LASIK", price: 2200 },
      { name: "Eye Exam", price: 150 },
      { name: "Retinal Laser", price: 800 },
      { name: "Intraocular Injection", price: 1200 },
    ],
    timelineEvents: ["Visual acuity tested", "Dilation performed", "Retina scanned", "Pressure checked", "Follow-up in 1 month"],
    patientNames: ["Arthur Pendelton", "Helen Troy", "Raymond Holt", "Diane Lockhart", "Walter Bishop"],
    doctorName: "Dr. Raymond",
  },
  {
    id: "orthopedics",
    name: "Orthopedics",
    icon: "🦴",
    emoji: "🦴",
    color: "bg-violet-500/15 text-violet-300",
    brief: {
      greeting: "Good morning",
      items: [
        "2 post-op knee reviews",
        "MRI result pending for shoulder",
        "Physio referral for 3 patients",
        "Fracture clinic at 3 PM",
      ],
      revenue: 8900,
    },
    conditions: ["Fracture", "Arthritis", "Sports Injury", "Herniated Disc", "Torn Meniscus", "Tendonitis"],
    procedures: ["Joint Replacement", "Arthroscopy", "Fracture Reduction", "Spine Surgery", "Casting"],
    labTypes: ["X-Ray", "MRI", "CT Scan", "Bone Density", "Joint Fluid Analysis"],
    billingItems: [
      { name: "Joint Replacement", price: 15000 },
      { name: "Arthroscopy", price: 5000 },
      { name: "Fracture Reduction", price: 1200 },
      { name: "MRI", price: 800 },
      { name: "Casting", price: 300 },
    ],
    timelineEvents: ["X-ray reviewed", "Range of motion assessed", "Surgery discussed", "Physiotherapy referred", "Follow-up in 6 weeks"],
    patientNames: ["Thomas Anderson", "Trinity Wells", "Morpheus King", "Niobe Cruz", "Jason Bourne"],
    doctorName: "Dr. Sarah",
  },
  {
    id: "neurology",
    name: "Neurology",
    icon: "🧠",
    emoji: "🧠",
    color: "bg-indigo-500/15 text-indigo-300",
    brief: {
      greeting: "Good morning",
      items: [
        "2 EEG reviews today",
        "MRI brain result received",
        "Migraine protocol review due",
        "Sleep study scheduled for Thursday",
      ],
      revenue: 6500,
    },
    conditions: ["Migraine", "Epilepsy", "Multiple Sclerosis", "Parkinson's", "Stroke Recovery", "Neuropathy"],
    procedures: ["EEG", "EMG", "Lumbar Puncture", "Nerve Conduction Study", "Neurological Exam"],
    labTypes: ["EEG", "EMG", "MRI Brain", "CT Brain", "Lumbar Puncture", "Sleep Study"],
    billingItems: [
      { name: "EEG", price: 400 },
      { name: "EMG", price: 350 },
      { name: "MRI Brain", price: 1200 },
      { name: "Lumbar Puncture", price: 600 },
      { name: "Consultation", price: 350 },
    ],
    timelineEvents: ["Neuro exam performed", "EEG reviewed", "Medication adjusted", "Cognitive test completed", "Follow-up in 3 months"],
    patientNames: ["Henry Watson", "Eliza Bennet", "Sebastian Michaelis", "Claire Redfield", "Leon Kennedy"],
    doctorName: "Dr. Balu",
  },
  {
    id: "endocrinology",
    name: "Endocrinology",
    icon: "🧬",
    emoji: "🧬",
    color: "bg-teal-500/15 text-teal-300",
    brief: {
      greeting: "Good morning",
      items: [
        "4 HbA1c results received",
        "Insulin titration review for 3 patients",
        "Thyroid panel pending",
        "Bone density scan scheduled",
      ],
      revenue: 4800,
    },
    conditions: ["Type 1 Diabetes", "Type 2 Diabetes", "Thyroid Disorder", "Osteoporosis", "PCOS", "Adrenal Insufficiency"],
    procedures: ["Insulin Adjustment", "Thyroid Ultrasound", "Bone Density Scan", "Hormone Panel Review"],
    labTypes: ["HbA1c", "Thyroid Panel", "Cortisol", "Bone Density", "Hormone Panel", "Glucose Tolerance Test"],
    billingItems: [
      { name: "Consultation", price: 300 },
      { name: "Thyroid Ultrasound", price: 450 },
      { name: "Bone Density Scan", price: 350 },
      { name: "Hormone Panel", price: 280 },
    ],
    timelineEvents: ["Blood glucose reviewed", "HbA1c trend analyzed", "Medication adjusted", "Diet discussed", "Follow-up in 90 days"],
    patientNames: ["Ahmed Hassan", "Grace Hopper", "Alan Turing", "Ada Lovelace", "Nikola Tesla"],
    doctorName: "Dr. Sarah",
  },
  {
    id: "obgyn",
    name: "Obstetrics & Gynecology",
    icon: "👩",
    emoji: "👩",
    color: "bg-rose-500/15 text-rose-300",
    brief: {
      greeting: "Good morning",
      items: [
        "3 prenatal checkups today",
        "Ultrasound at 11 AM",
        "Pap smear results received",
        "Postnatal follow-up at 3 PM",
      ],
      revenue: 5600,
    },
    conditions: ["Pregnancy", "PCOS", "Endometriosis", "Menopause", "Fibroids", "Infertility"],
    procedures: ["Ultrasound", "Pap Smear", "Prenatal Checkup", "Colposcopy", "Pelvic Exam"],
    labTypes: ["Ultrasound", "Pap Smear", "HPV Test", "Hormone Panel", "HCG Levels"],
    billingItems: [
      { name: "Ultrasound", price: 400 },
      { name: "Prenatal Checkup", price: 250 },
      { name: "Pap Smear", price: 180 },
      { name: "Colposcopy", price: 500 },
    ],
    timelineEvents: ["Ultrasound performed", "Fetal heartbeat confirmed", "Blood pressure checked", "Nutrition discussed", "Next visit in 4 weeks"],
    patientNames: ["Rebecca Martin", "Susan Mayer", "Bree Van De Kamp", "Lynette Scavo", "Gabrielle Solis"],
    doctorName: "Dr. Layla",
  },
  {
    id: "pulmonology",
    name: "Pulmonology",
    icon: "🫁",
    emoji: "🫁",
    color: "bg-blue-500/15 text-blue-300",
    brief: {
      greeting: "Good morning",
      items: [
        "2 spirometry results pending",
        "Sleep apnea review at 10 AM",
        "Chest X-ray received for review",
        "Oxygen therapy assessment due",
      ],
      revenue: 5400,
    },
    conditions: ["Asthma", "COPD", "Sleep Apnea", "Pneumonia", "Pulmonary Fibrosis"],
    procedures: ["Spirometry", "Bronchoscopy", "Sleep Study", "Oxygen Therapy Assessment", "Pulmonary Function Test"],
    labTypes: ["Spirometry", "Chest X-Ray", "CT Chest", "Sleep Study", "Arterial Blood Gas", "Sputum Culture"],
    billingItems: [
      { name: "Spirometry", price: 200 },
      { name: "Bronchoscopy", price: 1500 },
      { name: "Sleep Study", price: 1200 },
      { name: "Pulmonary Function Test", price: 450 },
    ],
    timelineEvents: ["Spirometry performed", "Oxygen saturation checked", "Inhaler technique reviewed", "Chest X-ray reviewed", "Follow-up in 1 month"],
    patientNames: ["Yusuf Al-Ghamdi", "Mariam Al-Qahtani", "Fred Flintstone", "Wilma Flintstone", "Barney Rubble"],
    doctorName: "Dr. Omar",
  },
  {
    id: "ent",
    name: "ENT",
    icon: "🧑‍⚕️",
    emoji: "👂",
    color: "bg-lime-500/15 text-lime-300",
    brief: {
      greeting: "Good morning",
      items: [
        "3 hearing tests today",
        "Tonsillectomy follow-up at 10 AM",
        "Audiometry results received",
        "Sinus CT scan pending review",
      ],
      revenue: 4300,
    },
    conditions: ["Hearing Loss", "Sinusitis", "Tonsillitis", "Tinnitus", "Vertigo", "Otitis Media"],
    procedures: ["Hearing Test", "Tonsillectomy", "Ear Tube Placement", "Sinus Surgery", "Endoscopy"],
    labTypes: ["Audiometry", "CT Sinus", "Tympanometry", "Throat Swab", "Nasal Endoscopy"],
    billingItems: [
      { name: "Audiometry", price: 180 },
      { name: "Tonsillectomy", price: 3000 },
      { name: "Ear Tube Placement", price: 2000 },
      { name: "Endoscopy", price: 500 },
    ],
    timelineEvents: ["Ear examined", "Hearing tested", "Endoscopy performed", "Medication prescribed", "Follow-up in 2 weeks"],
    patientNames: ["George Costanza", "Jerry Seinfeld", "Elaine Benes", "Cosmo Kramer", "Newman Postal"],
    doctorName: "Dr. Sarah",
  },
  {
    id: "gastroenterology",
    name: "Gastroenterology",
    icon: "🩺",
    emoji: "🫀",
    color: "bg-green-500/15 text-green-300",
    brief: {
      greeting: "Good morning",
      items: [
        "2 colonoscopy follow-ups today",
        "Endoscopy result received",
        "H. pylori test positive — treatment plan needed",
        "Liver function tests pending",
      ],
      revenue: 6200,
    },
    conditions: ["GERD", "IBS", "Crohn's Disease", "Ulcerative Colitis", "Hepatitis", "Celiac Disease"],
    procedures: ["Colonoscopy", "Endoscopy", "Liver Biopsy", "Capsule Endoscopy", "Sigmoidoscopy"],
    labTypes: ["Liver Function Test", "Stool Culture", "H. Pylori Test", "Colonoscopy", "Endoscopy", "Celiac Panel"],
    billingItems: [
      { name: "Colonoscopy", price: 1800 },
      { name: "Endoscopy", price: 1500 },
      { name: "Liver Biopsy", price: 800 },
      { name: "Consultation", price: 300 },
    ],
    timelineEvents: ["Procedure performed", "Biopsy sent", "Results reviewed", "Diet plan discussed", "Follow-up in 3 months"],
    patientNames: ["Homer Simpson", "Marge Simpson", "Ned Flanders", "Moe Szyslak", "Barney Gumble"],
    doctorName: "Dr. Sarah",
  },
  {
    id: "hematology",
    name: "Hematology",
    icon: "🩸",
    emoji: "🩸",
    color: "bg-red-500/15 text-red-300",
    brief: {
      greeting: "Good morning",
      items: [
        "CBC results received for 5 patients",
        "Iron infusion scheduled at 2 PM",
        "Coagulation panel pending",
        "Anemia follow-up due",
      ],
      revenue: 4900,
    },
    conditions: ["Anemia", "Leukemia", "Lymphoma", "Hemophilia", "Thrombocytopenia", "Polycythemia"],
    procedures: ["Bone Marrow Biopsy", "Iron Infusion", "Blood Transfusion", "Coagulation Study"],
    labTypes: ["CBC", "Coagulation Panel", "Iron Studies", "Bone Marrow Biopsy", "Blood Smear", "Flow Cytometry"],
    billingItems: [
      { name: "Bone Marrow Biopsy", price: 1200 },
      { name: "Iron Infusion", price: 500 },
      { name: "Blood Transfusion", price: 800 },
      { name: "Consultation", price: 350 },
    ],
    timelineEvents: ["Blood drawn", "CBC reviewed", "Transfusion completed", "Medication adjusted", "Follow-up in 1 month"],
    patientNames: ["Count Dracula", "Mina Harker", "Van Helsing", "Lucy Westenra", "Renfield"],
    doctorName: "Dr. Omar",
  },
  {
    id: "physiotherapy",
    name: "Physiotherapy",
    icon: "💆",
    emoji: "💆",
    color: "bg-purple-500/15 text-purple-300",
    brief: {
      greeting: "Good morning",
      items: [
        "6 therapy sessions today",
        "2 post-op knee rehab assessments",
        "Traction unit maintenance due",
        "Progress review for stroke patient",
      ],
      revenue: 2800,
    },
    conditions: ["Post-Surgical Rehab", "Sports Injury", "Stroke Recovery", "Chronic Back Pain", "Mobility Issues"],
    procedures: ["Manual Therapy", "Therapeutic Exercise", "Traction", "Ultrasound Therapy", "Electrical Stimulation"],
    labTypes: ["Range of Motion Assessment", "Muscle Strength Test", "Gait Analysis", "Functional Capacity Evaluation"],
    billingItems: [
      { name: "Therapy Session", price: 120 },
      { name: "Assessment", price: 200 },
      { name: "Traction", price: 80 },
      { name: "Electrical Stimulation", price: 90 },
    ],
    timelineEvents: ["Assessment completed", "Range of motion measured", "Therapy performed", "Home exercises prescribed", "Next session booked"],
    patientNames: ["Rocky Balboa", "Apollo Creed", "Clubber Lang", "Ivan Drago", "Adonis Creed"],
    doctorName: "Dr. Layla",
  },
  {
    id: "internal",
    name: "Internal Medicine",
    icon: "🩺",
    emoji: "🩺",
    color: "bg-stone-500/15 text-stone-300",
    brief: {
      greeting: "Good morning",
      items: [
        "5 chronic disease reviews today",
        "2 CBC results abnormal",
        "Comprehensive metabolic panel pending",
        "Medication reconciliation due for 3 patients",
      ],
      revenue: 5200,
    },
    conditions: ["Hypertension", "Diabetes", "Hyperlipidemia", "Chronic Kidney Disease", "Thyroid Disorder", "Gout"],
    procedures: ["Comprehensive Exam", "Medication Review", "Chronic Disease Management", "Preventive Screening"],
    labTypes: ["CBC", "Comprehensive Metabolic Panel", "Lipid Panel", "HbA1c", "TSH", "Vitamin D", "Urine Analysis"],
    billingItems: [
      { name: "Consultation", price: 250 },
      { name: "Comprehensive Exam", price: 400 },
      { name: "Medication Review", price: 150 },
      { name: "Preventive Screening", price: 500 },
    ],
    timelineEvents: ["Full history taken", "Physical exam completed", "Labs reviewed", "Medications adjusted", "Follow-up in 3 months"],
    patientNames: ["Walter White", "Jesse Pinkman", "Saul Goodman", "Mike Ehrmantraut", "Gus Fring"],
    doctorName: "Dr. Sarah",
  },
  {
    id: "oral-surgery",
    name: "Oral Surgery",
    icon: "🦷",
    emoji: "⚕️",
    color: "bg-slate-500/15 text-slate-300",
    brief: {
      greeting: "Good morning",
      items: [
        "2 wisdom tooth extractions today",
        "Implant placement at 11 AM",
        "CBCT scan received for jaw assessment",
        "Post-op review for bone graft patient",
      ],
      revenue: 9100,
    },
    conditions: ["Impacted Wisdom Tooth", "Jaw Cyst", "Facial Trauma", "Bone Loss", "Oral Lesion"],
    procedures: ["Wisdom Tooth Extraction", "Dental Implant", "Bone Grafting", "Jaw Surgery", "Cyst Removal"],
    labTypes: ["CBCT Scan", "Panoramic X-ray", "Biopsy", "Blood Work"],
    billingItems: [
      { name: "Wisdom Tooth Extraction", price: 600 },
      { name: "Dental Implant", price: 2200 },
      { name: "Bone Grafting", price: 800 },
      { name: "Jaw Surgery", price: 8000 },
    ],
    timelineEvents: ["Pre-op assessment", "Anesthesia administered", "Surgery completed", "Post-op instructions given", "Follow-up in 7 days"],
    patientNames: ["Harvey Specter", "Mike Ross", "Donna Paulsen", "Louis Litt", "Rachel Zane"],
    doctorName: "Dr. Ahmed",
  },
  {
    id: "multi",
    name: "Multi-Specialty",
    icon: "🏥",
    emoji: "🏥",
    color: "bg-foreground/10 text-foreground",
    brief: {
      greeting: "Good morning",
      items: [
        "12 appointments across 4 specialties",
        "Cardiology lab results pending",
        "Dental chair #2 needs maintenance",
        "Cross-referral from Pediatrics to ENT",
      ],
      revenue: 15600,
    },
    conditions: ["Diabetes", "Hypertension", "Root Canal", "Asthma", "Migraine", "Eczema", "Fracture"],
    procedures: ["Consultation", "ECG", "Dental Cleaning", "Vaccination", "X-Ray", "Skin Biopsy"],
    labTypes: ["CBC", "ECG", "X-Ray", "HbA1c", "Panoramic X-ray", "Skin Biopsy", "Audiometry"],
    billingItems: [
      { name: "Consultation", price: 200 },
      { name: "ECG", price: 150 },
      { name: "Dental Cleaning", price: 120 },
      { name: "X-Ray", price: 250 },
    ],
    timelineEvents: ["Patient registered", "Specialty assigned", "Consultation completed", "Cross-referral made", "Follow-up scheduled"],
    patientNames: ["Patient One", "Patient Two", "Patient Three", "Patient Four", "Patient Five", "Patient Six"],
    doctorName: "Dr. Team",
  },
];

export function getSpecialty(id: SpecialtyId | string): SpecialtyConfig {
  return SPECIALTIES.find((s) => s.id === id) || SPECIALTIES[0];
}
